pipeline:
  run-koa-react-starter-tests:
    image: node:10.11.0
    commands:
      - chmod +x ./bin/run.sh
      - ./bin/run.sh
    when:
      status: [ failure, success ]
      event: [ pull_request ]
