version: '3.6'  
services:
  redis:
    image: redis:5.0.0
    networks:
      - auxilin
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - "6379:6379" # map port to none standard port, to avoid conflicts with locally installed redis.
  web:
    build:
      context: "./"
      dockerfile: Dockerfile.dev
    volumes:
      - "./src:/app/src"
    networks:
      - auxilin
    environment:
      NODE_ENV: development
      HRM_HOST: "0.0.0.0"
    ports:
      - "3002:3002"
      - "8081:8081"

networks:
  auxilin:
    name: auxilin_network
